### PR TITLE
#5 it was already responsive but i enhancedit a little bit

### PR DESCRIPTION
**Pull request by Sky-De**
it is responsive already, and if you thinking about making background images responsive it is good practice if you provide diffrent sizes of your images based on your design then use picture tag and set them as srcSets , but there where some issues i fixed them

1. both pages had "already have and account ? ..." name , and also user can click all over text and btn 
for both pages

2. same thing like number 1 done for remember me check box

3. login signup now have space using gap instead of space-between

responssssssssssssssss

!!!!! you need merge second commit
thank you

### CODE REVIEW

**Review by SindhuraPogarthi — COMMENTED** [review]
Thank you so much for your contributon @Sky-De . I'm sorry i was not clear about specific page. I want the messages page to be responsive. It would be really helpul if you can do that.

**Review by SindhuraPogarthi — COMMENTED** [review]
Also about "already have an account?" and "don't have an account yet", i guess you have misplaced them. If the user already have an account he should get the option to login and if don't have an account yet the user should get signup option.

**Comment by Sky-De** [comment]
Hi again
sorry for confusion about "already have an account?" and "don't have an account yet", 
it is already fixed, but about making responsive msg component , it is responsive alredy too, you may need another design for these pages but in term of being responsive , there are




i did not change any thing, about this .
if you got any other prooblem about this commit let me know 
otherwise merge commit 3 
thanks

**Comment by SindhuraPogarthi** [comment]
The messages chat is not responsive as i have checked now it by inspecting. You can refer to the screenshot below.
Screenshot 2023-08-15 at 9 27 34 PM

**Comment by Sky-De** [comment]
@SindhuraPogarthi i can not reach this page with this content
all i can get is when i navagate manually through url to /messages
and it show just empty chat frame like as i sended before

qweqweqweqweqwe

Also i tried to login using mail or google none of them navigated me to messages page
i recommand you to clean up your code before adding more features.

Please make some note to clarify what exactly it works
thanks

**Comment by SindhuraPogarthi** [comment]
@Sky-De Firstly login with Google and then you get to see a page which consists of sidebar including sections like home,messages,notification,settings etc. Open the Messages section over there. You get to see the whole messages and chatting interface. Don't open the messages through routing because i have set the messages section such that the user can access messages only after successfull login.

**Comment by Sky-De** [comment]
@SindhuraPogarthi i did but unfortunately it doesn't work, none of your login methods, it just says done but it doesn't navigate to messages page
Even after login while there was no navigation to messages i just tried to navigate to messages manually but it was empty page as i sended screenshots
Check and inform me ty

**Comment by SindhuraPogarthi** [comment]
@Sky-De now i have improved the code related to naviagtion to mainpage. Now you can try logging in through google or by providing email and password. Now you can work upon this project. You hope you now can work on the project . Try to make the messages page responsive as soon as possible. Thank you .

**Pull request closed without merging**
